name: Reprod CI
on: [push, pull_request]

jobs:
  reprod:
    name: Reproduce Bug
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2

      - run: echo kotlin is awesome
